[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
"shared" = { path = "../shared" }
"cmdec" = { path = "../cmdec" }
"executor" = { path = "../executor" }

clap = { version = "~4.5", features = ["color", "derive", "debug"] }
log = "~0.4"
colog = "~1.3"
