[workspace]
resolver = "2"

members = [
    "cli",
    "cmdec",
    "executor",
    "stdlib",
    "shared",
    "macros/scope_dispatcher",
    "macros/manual_function_id",
    "tests",
]

[profile.profiling]
inherits = "release"
debug = true
