//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arc.Compiler.PackageGenerator.Models.Builtin {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArcStdlibSource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArcStdlibSource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Arc.Compiler.PackageGenerator.Models.Builtin.ArcStdlibSource", typeof(ArcStdlibSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] NamespaceMath {
            get {
                object obj = ResourceManager.GetObject("NamespaceMath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NamespaceArray {
            get {
                object obj = ResourceManager.GetObject("NamespaceArray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NamespaceCompilation {
            get {
                object obj = ResourceManager.GetObject("NamespaceCompilation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NamespaceConsole {
            get {
                object obj = ResourceManager.GetObject("NamespaceConsole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NamespaceCollectionLinkedList {
            get {
                object obj = ResourceManager.GetObject("NamespaceCollectionLinkedList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NamespaceCollectionList {
            get {
                object obj = ResourceManager.GetObject("NamespaceCollectionList", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
